Enable Python 3.9 in continuous integration
Frozen-Flask/Frozen-Flask pull request #110
Opened 2020-11-26 15:43 UTC by jayaddison

- Remove Python 3.5 continuous integration builds (it's now past end-of-life according to the Python [download page](https://www.python.org/downloads/))
- Enable Python 3.9

2020-11-26 16:02 UTC, honzajavorek requested changes

2020-11-26 16:02 UTC, honzajavorek commented on .github/workflows/main.yml
> +        python: [2.7, 3.6, 3.7, 3.8, 3.9, pypy3]
Removing 3.5 is a breaking change for frozen-flask, no matter the end of life. The policy is to follow whatever flask itself tests against. I'm inclined to releasing a breaking version, which would drop support for obsolete Python versions (opinions, @tswast?), but then let's do it properly. I quickly checked what versions are supported by flask and it seems they might have dropped even the 2.x line 😮 

So my idea would be that we add support for 3.9 and release a minor version. Then we could prepare a version, which drops all the old stuff unsupported by Flask, and only then release a breaking version.

2020-11-26 16:06 UTC, honzajavorek commented
OK I now noticed that frozen-flask is version 0.15, so I'm not sure how closely it follows the semantic versioning scheme. I think a project used by ~2000 ppl and with history going back to 2011 deserves to take off with a "stable" v1.0.0, with which we could drop the old Python version, and from which we could follow with sem ver.

2020-11-26 16:10 UTC, jayaddison commented
Ah, I just missed your latest comment before pushing changes.  Will pause to hear the preferred approach.

2020-11-26 16:21 UTC, honzajavorek commented
I think we can add 3.9 just fine, but we should sync on how to drop the old
stuff before doing that.

On Thu 26. 11. 2020 at 17:10, James Addison <notifications@github.com>
wrote:

> Ah, I just missed your latest comment before pushing changes. Will pause
> to hear the preferred approach.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Frozen-Flask/Frozen-Flask/pull/110#issuecomment-734383205>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACFGMNNKF7ESMLRFELBQ6DSRZ4YJANCNFSM4UD4NDXQ>
> .
>

2020-11-26 16:22 UTC, honzajavorek approved these changes

2020-11-26 16:22 UTC, merged

2021-01-12 01:16 UTC, jayaddison commented
@tswast @honzajavorek Not urgent, but I'm wondering if there's been any further discussion about releasing an updated minor version of `frozen-flask` with Python 3.9 support?

2021-01-12 18:23 UTC, tswast commented
>  I'm wondering if there's been any further discussion about releasing an updated minor version of frozen-flask with Python 3.9 support?

I may have missed it, but were there PRs to fix the library to support Python 3.9? Even without the 3.9 classifier in [`setup.py`](https://github.com/Frozen-Flask/Frozen-Flask/blob/master/setup.py), it should be possible to install on 3.9, since there isn't a `python_requires` field that would prevent it.

2021-01-12 18:44 UTC, jayaddison commented
@tswast Yep; my understanding (which may have clouded over a bit since I last looked into this) is that #98 added Py3.9 compatibility, and since then #107 has fixed an incompatibility encountered when using Py2.7.

To be thorough perhaps we should go back and discover when those test failures for Py2.7 began and understand that before a release; the issue relates to handling of multi-byte unicode characters in URLs.

2021-01-12 19:13 UTC, jayaddison commented
(taking a look into this now, to try to identify what initially caused the Py2.7 test failures)

2021-01-12 19:38 UTC, jayaddison commented
Ok, so the test was introduced a while back in b43242a75686af49c7a38a865c0d4ec62293571f in May 2011, and while it's neat that it uses Unicode everywhere, I think Python 2.7's `urllib.unquote` is behaving within the URI spec as-written.  Perhaps only IRIs may contain multibyte characters?